### ISSUE TITLE
Improve consistency on DD and CDM

### ISSUE THREAD

**Issue by Cyb3rWard0g** [OTRF/OSSEM-DD#32]
Example:

AWS Cloud Trail Log

https://github.com/OTRF/OSSEM-DD/blob/9837f875b0c114de827989da9724ddfe737a706b/aws/events/cloudtrail.yml#L4

CDM
https://github.com/OTRF/OSSEM-DM/blob/55b9d57924ff089cd273878fdbc1de8962d19de9/relationships/user_retrieved_information_about_cloud_service.yml#L18

**Comment by Cyb3rWard0g** [comment]
Event_Code -> Event ID

**Comment by Cyb3rPandaH** [comment]
Issue solved in developer branch :)
